apiVersion: v1
kind: Pod
metadata:
  name: demo-bad-pod
  namespace: demo
spec:
  containers:
    - image: image-registry.openshift-image-registry.svc:5000/demo/demo
      name: demo
      args:
        - /log/demologs.log
      volumeMounts:
        - name: logs
          mountPath: /log/
      securityContext:
        seccompProfile:
          type: Localhost
          # NOTE: This uses an appropriate Seccomp profile
          localhostProfile: operator/demo/demo/seccomp-demo.json
        seLinuxOptions:
          # NOTE: This uses an appropriate SELinux type
          type: errorlogger_demo.process
  restartPolicy: Never
  volumes:
    - name: logs
      hostPath:
        # NOTE: This writes to the audit logs!
        # this was probably not intended by the application
        # developers.
        path: /var/log/audit/
        type: Directory