apiVersion: v1
kind: Pod
metadata:
  name: demo
  namespace: demo
spec:
  containers:
    - image: image-registry.openshift-image-registry.svc:5000/demo/demo
      name: demo
      args:
        - /log/demologs.log
      volumeMounts:
        - name: logs
          mountPath: /log/
      securityContext:
        #seccompProfile:
        #  type: Localhost
        #  # NOTE: This uses an appropriate Seccomp profile
        #  localhostProfile: operator/demo/seccomp-demo.json
        seLinuxOptions:
          # NOTE: This uses an appropriate SELinux type
          type: errorlogger_security-profiles-operator.process
  restartPolicy: Never
  volumes:
    - name: logs
      hostPath:
        # NOTE: this writes to the normal logs as expected
        path: /var/log/
        type: Directory
