apiVersion: v1
kind: Pod
metadata:
  name: demo
  namespace: record-demo
  labels:
    app: demo
spec:
  containers:
    - image: quay.io/jhrozek/spo-demo:latest
      name: demo
      args:
        - /log/demologs.log
      volumeMounts:
        - name: logs
          mountPath: /log/
      securityContext:
        seLinuxOptions:
          # NOTE: This uses an appropriate SELinux type
          type: test-recording-demo_record-demo.process
  restartPolicy: Never
  volumes:
    - name: logs
      hostPath:
        path: /var/log/
        type: Directory
